### ISSUE TITLE
[Q] - Is it possible to add composer.json dependencies with this image?

### ISSUE THREAD

**Issue by fritzvd** [jitesoft/docker-phpunit#1]
I've been using the jitesoft/phpunit image for a few days now, and it's been wonderful:
```bash
docker run -v $(pwd):/app --platform linux/amd64 --rm jitesoft/phpunit phpunit --configuration phpunit.xml
```
And voila. But I'm running into some problems when I try to add some validation of html with things like tidy or external packages.

Is there a way to tell the image to use a seperate .ini file or composer.json? Or should I just build my own image dependent on this one?

**Comment by Johannestegner** [comment]
Hi there!
Happy to hear that you enjoy the image! :)

Composer is included in the image, so installing composer packages can be done right away. If you wish to change the ini files I would say that the easiest way is to add a ini file to the `/usr/local/etc/php/conf.d/` directory. All files in that directory are auto-loaded.

Extensions can be installed through the `php-ext` command if needed :)

Depending on how you use the image (that is, if you need to install composer packages inside the image or similar) I would either create a script which you could use as entrypoint (a a/sh script or similar) or manually install the composer packages before running the image.
Composer packages are not installed by default.

Further, the image is based on the jitesoft/composer image (which installs composer) which in turn is based on the jitesoft/php (cli) image, which installs php and some common extensions. X-Debug should be installed by default in the image, but no more major specific extensions.

If you need extensions other than the default ones, the absolute easiest way would to extend the image with something like:

```dockerfile
FROM jitesoft/phpunit

RUN php-ext install <extension>
```
